### ISSUE TITLE
Data Input - Employee

### ISSUE THREAD

**Issue by james-mcallister** [james-mcallister/malt#1]
## Title
Data Input - Employee

## User Story
As a user, I want to enter information about an employee so that I can plan and analyze their labor.

## Acceptance Criteria
Given an input form on a graphical user interface (GUI),
When employee information is entered,
Then the application view should display the employee information,
  And the application should store the employee information.

**Estimate**: 5
**Priority**: HIGH
**Depends On**: N/A

#### Sub-Tasks
- [ ] Design Diagram updated in SW Architecture doc

#### Definition of Done
- [ ] Sub-Tasks are complete
- [ ] New tests are added or updated that verify the acceptance criteria
- [ ] All unit tests pass
- [ ] Code Coverage is updated
- [ ] Documentation is added or updated. Specifically, ensure the changelog is updated
