### ISSUE TITLE
Data Input - Labor Hours

### ISSUE THREAD

**Issue by james-mcallister** [james-mcallister/malt#2]
## Title
Data Input - Labor Hours

## User Story
As a user, I want to input labor hours for an employee so that I can plan the labor on my project.

## Acceptance Criteria
Given an input form on a GUI,
When an employees labor hours information is entered,
Then the application view should show the labor hours information,
  And the application should store the labor hours information.

**Estimate**: 3
**Priority**: HIGH
**Depends On**: N/A

#### Sub-Tasks
- [x] Design Diagram is updated in SW Architecture doc

#### Definition of Done
- [x] Sub-Tasks are complete
- [x] New tests are added or updated that verify the acceptance criteria
- [x] All unit tests pass
- [x] Code Coverage is updated
- [x] Documentation is added or updated. Specifically, ensure the changelog is updated

**Comment by james-mcallister** [comment]
completed on #46
