### ISSUE TITLE
Data Input - Project

### ISSUE THREAD

**Issue by james-mcallister** [james-mcallister/malt#4]
## Title
Data Input - Project

## User Story
As a user, I want to enter information about a project so that I can plan the project’s labor needs.

## Acceptance Criteria
Given an input form on the GUI,
When the project information is entered,
Then the application should store the project information,
  And the application view should display the project information.

**Estimate**: 5
**Priority**: HIGH
**Depends On**: N/A

#### Sub-Tasks
- [x] Update design diagrams

#### Definition of Done
- [x] Sub-Tasks are complete
- [x] New tests are added or updated that verify the acceptance criteria
- [x] All unit tests pass
- [x] Code Coverage is updated
- [x] Documentation is added or updated. Specifically, ensure the changelog is updated
