### ISSUE TITLE
Data Input - Calendar

### ISSUE THREAD

**Issue by james-mcallister** [james-mcallister/malt#7]
## Title
Data Input - Calendar

## User Story
As a user, I want to specify a calendar so that the labor hours and expenditures are based on a customizable work week and pay period.

## Acceptance Criteria
Given an application configuration dialog,
When a preconfigured calendar is selected,
  Or a calendar is manually configured,
Then the application reporting tools should utilize the configured calendar.

**Estimate**: 8
**Priority**: HIGH
**Depends On**: #21 

#### Sub-Tasks
- [x] Data Model that includes database tables for calendar functionality
- [x] Design Class diagram for model
- [x] Preliminary UI design for calendar
- [x] Classes related to data input for calendar are created

#### Definition of Done
- [x] Sub-Tasks are complete
- [x] New tests are added or updated that verify the acceptance criteria
- [x] All unit tests pass
- [x] Code Coverage is updated
- [x] Documentation is added or updated. Specifically, ensure the changelog is updated

**Comment by james-mcallister** [comment]
completed in pull request #40
